#!/bin/sh

# Exit on errors
trap 'fail' ERR
fail () {
    code=$?
    echo "Failed with exit code $code"
    exit 1
}

if test -z "$SMOKE_GIT"; then
    echo "$0: You must supply a path to a Git as SMOKE_GIT="
    exit 1
fi

chown -Rv smolder:smolder $SMOKE_GIT/.git
chmod -Rv g+rw $SMOKE_GIT/.git
