#!/bin/sh

# Exit on errors
trap 'fail' ERR
fail () {
    code=$?
    echo "Failed with exit code $code"
    exit 1
}

if test -z "$SMOKE_REPORTS"; then
    echo "$0: You must supply a path to SMOKE_REPORTS"
    exit 1
fi

TO=$(mktemp -d smolder-reports.XXXX)

rsync -av \
    --progress --stats \
    --exclude=*tap \
    --exclude=*html \
    $SMOKE_REPORTS \
	$TO
